import type { LocalExplanation } from "../../types/explainability";

function Factors({ title, factors }: { title: string; factors: LocalExplanation["feature_contributions"] }) {
  return <section><h3>{title}</h3>{factors.length === 0 ? <p>None identified.</p> : <ul>{factors.map((factor) => <li key={factor.feature}>{factor.feature}: {factor.contribution.toFixed(4)}</li>)}</ul>}</section>;
}

export default function ShapChart({ explanation }: { explanation: LocalExplanation }) {
  const signed = explanation.method === "linear_coefficients" || explanation.method.toLowerCase().includes("shap");
  return <section className="card local-explanation"><span className="card-kicker">LOCAL EXPLANATION</span><h2>Selected row prediction</h2><div className="stage-kpis"><article><span>Method</span><strong>{explanation.method.replaceAll("_", " ")}</strong></article><article><span>Prediction</span><strong>{String(explanation.prediction)}</strong></article>{explanation.prediction_probability !== null && <article><span>Probability</span><strong>{(explanation.prediction_probability * 100).toFixed(1)}%</strong></article>}</div>{explanation.predicted_value !== null && <p>Predicted value: {String(explanation.predicted_value)}</p>}{signed ? <><Factors title="Factors increasing this output" factors={explanation.top_positive_factors} /><Factors title="Factors decreasing this output" factors={explanation.top_negative_factors} /></> : <><h3>Local importance proxy</h3><div className="proxy-factors">{explanation.feature_contributions.map((factor) => <div className="importance-row" key={factor.feature}><span>{factor.feature}</span><div className="importance-track"><span style={{width:`${Math.min(100, factor.importance * 100)}%`}} /></div><small>{factor.importance.toFixed(4)}</small></div>)}</div><p className="info-callout">These values indicate relative local importance only; they do not reliably show whether a feature increased or decreased the prediction.</p></>}{explanation.warnings.map((warning) => <p className="configuration-warning" key={warning}>{warning}</p>)}</section>;
}
