import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getFinalReport, type FinalReportResponse } from "../services/datasetService";
import { getProfile, getVisualInsights, type VisualInsights } from "../services/profileService";
import type { DatasetProfile, ProfileValue } from "../types/profile";

const labels: Record<string, string> = { profile: "Dataset Profile", configuration: "Analysis Configuration", capabilities: "ACSA Decisions", workflow: "AWGA Workflow", pruned_workflow: "Optimized Workflow", execution: "Execution Summary", model_recommendations: "AMRA Recommendations", model_evaluation: "Model Evaluation", explainability: "Explainability", business_priority: "CIPS Priorities" };
const number = (item: number | null | undefined, digits = 0) => item == null || !Number.isFinite(item) ? "—" : new Intl.NumberFormat(undefined, { maximumFractionDigits: digits }).format(item);
const value = (item: ProfileValue | undefined) => item == null ? "—" : String(item);
const title = (item: string) => item.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function StageSummary({ name, stage }: { name: string; stage: unknown }) {
  if (!stage) return <article className="report-stage report-stage-empty"><h3>{labels[name] ?? title(name)}</h3><p>Not completed for this analysis.</p></article>;
  const record = typeof stage === "object" && stage !== null && !Array.isArray(stage) ? stage as Record<string, unknown> : {};
  const facts = Object.entries(record).filter(([, item]) => ["string", "number", "boolean"].includes(typeof item)).slice(0, 4);
  return <article className="report-stage"><p className="report-stage-label">{name.replaceAll("_", " ")}</p><h3>{labels[name] ?? title(name)}</h3>{facts.length ? <dl>{facts.map(([key, item]) => <div key={key}><dt>{title(key)}</dt><dd>{String(item)}</dd></div>)}</dl> : <p>Result available in the analysis record.</p>}</article>;
}

function ProfileVisuals({ profile, insights }: { profile: DatasetProfile; insights: VisualInsights | null }) {
  const types = [["Numerical", profile.summary.numerical_columns, "lime"], ["Categorical", profile.summary.categorical_columns, "cyan"], ["Boolean", profile.summary.boolean_columns, "amber"], ["Date / text", profile.summary.datetime_columns + profile.summary.text_columns, "slate"]] as const;
  const total = Math.max(profile.summary.columns, 1);
  const missing = Object.entries(profile.quality.missing_values.by_column).filter(([, info]) => info.missing_count > 0).sort((a, b) => b[1].missing_percentage - a[1].missing_percentage).slice(0, 8);
  const correlations = profile.correlations.pairs.filter((pair) => pair.correlation !== null).sort((a, b) => Math.abs(b.correlation ?? 0) - Math.abs(a.correlation ?? 0)).slice(0, 6);
  const histogram = profile.column_types.map((column) => profile.columns[column.column]).find((column) => column?.distribution?.histogram);
  const counts = histogram?.distribution?.histogram?.counts ?? [];
  const maxCount = Math.max(...counts, 1);
  return <>
    <section className="report-section report-executive"><div><p className="eyebrow">EXECUTIVE SNAPSHOT</p><h2>Data readiness at a glance</h2><p>The profile below is generated from the uploaded file. Visuals appear only where the data supports that analysis.</p></div><div className="report-score"><strong>{Math.max(0, 100 - profile.summary.missing_percentage - profile.summary.duplicate_percentage).toFixed(0)}</strong><span>readiness score</span></div></section>
    <section className="report-kpis"><article><span>Rows analysed</span><strong>{number(profile.summary.rows)}</strong></article><article><span>Columns profiled</span><strong>{number(profile.summary.columns)}</strong></article><article><span>Missing cells</span><strong>{number(profile.summary.missing_cells)}</strong><small>{number(profile.summary.missing_percentage, 2)}%</small></article><article><span>Duplicate rows</span><strong>{number(profile.summary.duplicate_rows)}</strong><small>{number(profile.summary.duplicate_percentage, 2)}%</small></article></section>
    <section className="report-chart-grid"><article className="report-section"><p className="eyebrow">SCHEMA</p><h2>Attribute mix</h2><div className="report-type-bars">{types.map(([label, count, tone]) => <div key={label}><span>{label}</span><i><b className={tone} style={{ width: `${count / total * 100}%` }} /></i><strong>{count}</strong></div>)}</div></article><article className="report-section"><p className="eyebrow">DATA QUALITY</p><h2>Missingness by column</h2>{missing.length ? <div className="report-bars">{missing.map(([column, info]) => <div key={column}><span title={column}>{column}</span><i><b style={{ width: `${Math.max(2, info.missing_percentage)}%` }} /></i><strong>{number(info.missing_percentage, 1)}%</strong></div>)}</div> : <p className="report-empty">No missing values were detected.</p>}</article></section>
    <section className="report-chart-grid"><article className="report-section"><p className="eyebrow">RELATIONSHIPS</p><h2>Strongest correlations</h2>{correlations.length ? <div className="report-bars correlation-report-bars">{correlations.map((pair) => <div key={`${pair.feature_1}-${pair.feature_2}`}><span>{pair.feature_1} × {pair.feature_2}</span><i><b className={(pair.correlation ?? 0) < 0 ? "negative" : ""} style={{ width: `${Math.abs(pair.correlation ?? 0) * 100}%` }} /></i><strong>{number(pair.correlation, 2)}</strong></div>)}</div> : <p className="report-empty">Correlation requires at least two suitable numerical columns.</p>}</article><article className="report-section"><p className="eyebrow">DISTRIBUTION</p><h2>{histogram?.column ?? "Numerical distribution"}</h2>{counts.length ? <div className="report-histogram" role="img" aria-label={`Histogram for ${histogram?.column}`}>{counts.map((count, index) => <i key={index} style={{ height: `${Math.max(3, count / maxCount * 100)}%` }} title={`${count} values`} />)}</div> : <p className="report-empty">A histogram appears when a numerical feature is available.</p>}</article></section>
    {insights?.target_distribution.length ? <section className="report-section"><p className="eyebrow">TARGET ANALYSIS</p><h2>{insights.target} distribution</h2><div className="report-bars">{insights.target_distribution.map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.percentage}%` }} /></i><strong>{number(item.percentage, 1)}%</strong></div>)}</div></section> : null}
  </>;
}

export default function Report() {
  const { datasetId } = useParams<{ datasetId: string }>(); const [data, setData] = useState<FinalReportResponse | null>(null); const [profile, setProfile] = useState<DatasetProfile | null>(null); const [insights, setInsights] = useState<VisualInsights | null>(null);
  useEffect(() => { if (datasetId) void Promise.all([getFinalReport(datasetId), getProfile(datasetId).catch(() => null), getVisualInsights(datasetId).catch(() => null)]).then(([report, loadedProfile, loadedInsights]) => { setData(report); setProfile(loadedProfile); setInsights(loadedInsights); }); }, [datasetId]);
  const completedStages = useMemo(() => data ? Object.entries(data.stages).filter(([, stage]) => Boolean(stage)) : [], [data]);
  if (!data) return <main className="page">Loading report…</main>;
  return <main className="page report-page"><div className="report-actions"><Link to={`/datasets/${datasetId}/research`}>← Back to research</Link><button type="button" onClick={() => window.print()}>Download / Print PDF</button></div><header className="report-cover"><p>AWOF · ADAPTIVE WORKFLOW OPTIMIZATION FRAMEWORK</p><h1>Analysis report</h1><h2>{data.dataset.original_filename}</h2><div><span>{data.dataset.rows.toLocaleString()} rows</span><span>{data.dataset.columns.toLocaleString()} columns</span><span>{completedStages.length} completed stages</span></div></header>{profile ? <ProfileVisuals profile={profile} insights={insights} /> : <section className="report-section"><h2>Profile visualisations unavailable</h2><p>Generate Dataset Intelligence to include data-quality and distribution charts in this report.</p></section>}<section className="report-section report-stage-section"><div><p className="eyebrow">ANALYSIS TRACE</p><h2>Workflow results</h2><p>Each completed stage is summarised below; unavailable stages remain explicitly marked.</p></div><div className="report-stage-grid">{Object.entries(data.stages).map(([name, stage]) => <StageSummary key={name} name={name} stage={stage} />)}</div></section><section className="report-section"><p className="eyebrow">LIMITATIONS</p><h2>Interpretation notes</h2><ul className="report-limitations">{data.limitations.map((item) => <li key={item}>{item}</li>)}</ul></section></main>;
}
